<?php

namespace AppBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
	public function companyById($idCompany)
	{
		return $this->createQueryBuilder('c')
			->setParameter('id', $idCompany)
			->where('c.id = :id')
			->getQuery()
			->getResult();
	}

}
