<?php

namespace AppBundle\Repository;

/**
 * DictionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByType($type){
            return $this->createQueryBuilder('d')
                ->setParameter('type', $type)
                ->where('d.type = :type')
                ->getQuery()
                ->getResult();

    }

}
