<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Dictionary;

/**
 * DictionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTheme(){
		$qb = $this->createQueryBuilder('d')
			->setParameter('type', Dictionary::TYPE_THEME)
			->where('d.type = :type')
			->getQuery();
		return $qb->getResult();
	}

    public function findByType($type){
            return $this->createQueryBuilder('d')
                ->setParameter('type', $type)
                ->where('d.type = :type')
                ->getQuery()
                ->getResult();

    }
}
