<?php

namespace AppBundle\Repository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFavoriteByUserId($idUser)
    {
        return $this->createQueryBuilder('f')
            ->setParameter('idUser', $idUser)
            ->where('f.user = :idUser')
            ->getQuery()
            ->getResult();
    }
}
