<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use AppBundle\Entity\User;
use DateInterval;
use DateTime;


/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    const MAX_PROJECT = 3;

    const CHAMPS = ["title", "descResume"];

    public function statProject()
    {
        $result['project']['total'] = count($this->createQueryBuilder('p')
            ->getQuery()
            ->getResult());
        $result['project']['publish'] = count($this->createQueryBuilder('p')
            ->setParameter('status', Project::STATUS_PUBLISH)
            ->where('p.status = :status')
            ->getQuery()
            ->getResult());
        $result['project']['waiting'] = count($this->createQueryBuilder('p')
            ->setParameter('status', Project::STATUS_WAITING)
            ->where('p.status = :status')
            ->getQuery()
            ->getResult());
        $result['project']['draft'] = count($this->createQueryBuilder('p')
            ->setParameter('status', Project::STATUS_DRAFT)
            ->where('p.status = :status')
            ->getQuery()
            ->getResult());
        $mois = array("", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre");
        $dateStat = [];
        for ($i = 0; $i < 6; $i++) {
            $max = new DateTime('last day of today - ' . $i . ' month');
            $min = new DateTime('last day of today - ' . ($i + 1) . ' month');

            $dateStat[$mois[$max->format('n')]] = count($this->createQueryBuilder('p')
                ->setParameter('maxDate', $max)
                ->andWhere('p.creationDate < :maxDate')
                ->setParameter('minDate', $min)
                ->andWhere('p.creationDate > :minDate')
                ->getQuery()
                ->getResult());
        }
        $result['project']['history'] = $dateStat;

        $result['user']['Actif'] = count($this->getEntityManager()
            ->getRepository('AppBundle:User')
            ->createQueryBuilder('u')
            ->setParameter('status', User::USER_STATUS_ACTIF)
            ->andWhere('u.status = :status')
            ->getQuery()
            ->getResult());
        $result['user']['Inactif'] = count($this->getEntityManager()
            ->getRepository('AppBundle:User')
            ->createQueryBuilder('u')
            ->setParameter('status', User::USER_STATUS_INACTIF)
            ->andWhere('u.status = :status')
            ->getQuery()
            ->getResult());
        $result['user']['Supprimer'] = count($this->getEntityManager()
            ->getRepository('AppBundle:User')
            ->createQueryBuilder('u')
            ->setParameter('status', User::USER_STATUS_DELETE)
            ->andWhere('u.status = :status')
            ->getQuery()
            ->getResult());
        $result['lastLogin'] = $this->getEntityManager()
            ->getRepository('AppBundle:User')
            ->createQueryBuilder('u')
            ->orderBy('u.lastLogin', 'DESC')
            ->setMaxResults(14)
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function getLastProject()
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy("p.updateDate", "DESC")
            ->setMaxResults(self::MAX_PROJECT)
            ->setParameter('status', Project::STATUS_PUBLISH)
            ->where('p.status = :status')
            ->getQuery();
        return $qb->getResult();
    }

    public function getProjectOrderBY($field)
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy("p.$field", "ASC")
            ->getQuery();
        return $qb->getResult();
    }

    public function projectById($idProject)
    {
        return $this->createQueryBuilder('p')
            ->setParameter('id', $idProject)
            ->where('p.id = :id')
            ->getQuery()
            ->getResult();
    }

    public function getImageProject($idProject)
    {
        return $this->createQueryBuilder('p')
            ->setParameter('id', $idProject)
            ->where('p.id = :id')
            ->select('p.images')
            ->getQuery()
            ->getResult();
    }

    public function getProjectByMayor($mayorId)
    {
        $qb = $this->createQueryBuilder('p')
            ->setParameter('mayor_id', $mayorId)
            ->where('p.mayor = :mayor_id')
            ->getQuery();
        return $qb->getResult();
    }

    public function findByTextPertinence($texts, $champs)
    {
        $results = [];
        $texts = explode(' ', $texts);
        $qb = $this->createQueryBuilder('p');
        foreach ($texts as $text) {
            if (strlen($text) > 2) {
                $qb->select('p.id');
                $qb->setParameter('text', '%' . $text . '%');
                foreach ($champs as $champ) {
                    $qb->where("p.$champ LIKE :text");
                    $qb->andWhere('p.status = ' . Project::STATUS_PUBLISH);
                    $query = $qb->getQuery();
                    $results[count($results) + 1] = $query->getResult();
                    if (empty ($results[count($results)])) {
                        unset($results[count($results)]);
                    }
                }
            }
        }
        return $results;
    }

    public function findByThemaPertinence($themas)
    {
        $results = "";
        foreach ($themas as $thema) {

            $sql = " SELECT id FROM project_theme WHERE themes = $thema";
            $em = $this->getEntityManager();
            $stmt = $em->getConnection()->prepare($sql);
            $stmt->execute();
            $results = $stmt->fetchAll();

        }
        $cleanResult = "";
        foreach ($results as $key => $project) {
            $i = 0;
            $cleanResult[$i] = [];
            foreach ($project as $id) {
                array_push($cleanResult[$i], ['id' => $id]);
            }
            $i++;
        }

        return $cleanResult;
    }

    public function findByKeywordPertinence($themas)
    {
        $results = "";
        foreach ($themas as $thema) {

            $sql = " SELECT id FROM project_keywords WHERE keyWords = $thema";
            $em = $this->getEntityManager();
            $stmt = $em->getConnection()->prepare($sql);
            $stmt->execute();
            $results = $stmt->fetchAll();


        }
        $cleanResult = "";
        foreach ($results as $key => $project) {
            $i = 0;
            $cleanResult[$i] = [];
            foreach ($project as $id) {
                array_push($cleanResult[$i], ['id' => $id]);
            }
            $i++;
        }

        return $cleanResult;
    }

    public function findByLocalisationPertinence($locals)
    {
        $results = [];
        foreach ($locals as $key => $values) {
            switch ($key) {
                case Project::LOCALISATION_COMMUNE:
                    $value = explode(' ', $values);
                    $mayorIds = $this->getEntityManager()
                        ->createQuery('SELECT pm.id FROM AppBundle:Mayor pm WHERE pm.zipCode = ' . $value[0])
                        ->getResult();

                    foreach ($mayorIds as $value) {
                        $qb = $this->createQueryBuilder('p');
                        $qb->select('p.id')
                            ->setParameter('mayor', $value['id'])
                            ->where('p.mayor = :mayor')
                            ->getQuery();
                        $query = $qb->getQuery();
                        $results[] = $query->getResult();
                    }


                    break;
                case Project::LOCALISATION_DEPARTEMENT:
                    $value = explode(' ', $values);
                    $mayorIds = $this->getEntityManager()
                        ->createQuery('SELECT pm.id FROM AppBundle:Mayor pm WHERE pm.department = ' . $value[0])
                        ->getResult();


                    foreach ($mayorIds as $value) {
                        $qb = $this->createQueryBuilder('p');
                        $qb->select('p.id')
                            ->setParameter('mayor', $value['id'])
                            ->where('p.mayor = :mayor')
                            ->getQuery();
                        $query = $qb->getQuery();
                        $results[] = $query->getResult();
                    }

                    break;
                case Project::LOCALISATION_REGION:
                    $value = explode(' ', $values);
                    $mayorIds = $this->getEntityManager()
                        ->createQuery('SELECT pm.id FROM AppBundle:Mayor pm WHERE pm.region = ' . $value[0])
                        ->getResult();

                    foreach ($mayorIds as $value) {
                        $qb = $this->createQueryBuilder('p');
                        $qb->select('p.id')
                            ->setParameter('mayor', $value['id'])
                            ->where('p.mayor = :mayor')
                            ->getQuery();
                        $query = $qb->getQuery();
                        $results[] = $query->getResult();
                    }


                    break;
            }
        }
        return $results;
    }

    public function arrayCleaner($array)
    {
        $result = [];
        foreach ($array as $key => $value) {
            if ($value !== []) {
                array_push($result, $value[0]['id']);
            }
        }

        return $result;
    }
}
