<?php

namespace AppBundle\Repository;

use function array_push;
use function get_object_vars;

/**
 * PublicPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicPageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getContentIndex(array $args)
	{

		$result = [];
		foreach ($args as $arg) {
			$qb = $this->createQueryBuilder('c');
			$qb->setParameter('name', $arg);
			$qb->where('c.name = :name');
			$query = $qb->getQuery();
			$result[$arg] = $query->getResult();
		}
		$realResult = [];
		foreach ($result as $argument => $objects) {
			foreach ($objects as $key => $object) {
				$realResult[$argument] = $object;
			}
		}
		return $realResult;
	}
}
