<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
 /*   public function getUserPartner($idPartner)
    {
        return $this->createQueryBuilder('u')
            ->where('u.partner_id = :idPartner')
            ->setParameter('idPartner', $idPartner)
            ->getQuery()
            ->getResult();
    }*/
}
