$(function(){
    var availableTags = [
        "école",
        "périscolaire",
        "formation",
        "crèche",
        "restauration scolaire",
        "médecin",
        "maison de santé",
        "infirmiers",
        "professionnels de santé",
        "maison de services publics",
        "commerces",
        "Etat civil",
        "manifestations citoyennes",
        "vie associative",
        "economie sociale et solidaire",
        "élections",
        "cérémonie",
        "parcs régionaux",
        "espaces verts",
        "écologie",
        "développement durable",
        "urbanisme",
        "rénovation/réfection",
        "transports",
        "voirie",
        "voies navigables",
        "intermodalités",
        "transports",
        "station service",
        "patrimoine",
        "valorisation du territoire",
        "église",
        "logements sociaux",
        "EHPAD",
        "maisons de quartier",
        "CCAS",
        "emploi",
        "entreprises",
        "startups",
        "espace de coworking",
        "télétravail",
        "lecture",
        "festival",
        "musique",
        "cinema",
        "théâtre",
        "haut débit",
        "application",
        "digital",
        "téléphonie mobile",
        "téléphonie fixe",
        "innovation",
        "internet",
        "SPANC",
        "Station d'épuration ",
        "réseaux",
        "Coopération décentralisée",
        "Arménie",
        "Europe",
        "Jumelage"
    ];
    $('#motsCle').autocomplete({
        source: availableTags,
        multiselect: true
    });


});