<?php

namespace AMRF\PublicRooterBundle\Repository;

/**
 * MayorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MayorRepository extends \Doctrine\ORM\EntityRepository
{
}
