<?php

namespace AMRF\PublicRooterBundle\Repository;

/**
 * PublicPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicPageRepository extends \Doctrine\ORM\EntityRepository
{
}
